### ISSUE TITLE
A model with ServiceInterface suffix considered as an API subject

### ISSUE THREAD

**Issue by PhilinTv** [spryker/code-sniffer#106]
A model like ModelServiceInterface will cause a CS issue, which requires methods to be marked '@api' tag. I guess it's a suffix issue.

Example: https://github.com/spryker-middleware/process/pull/16#discussion-diff-160165316R13

**Comment by dereuromark** [comment]
Same with
```
namespace Spryker\Client\Storage\Redis;

interface ServiceInterface
```

The only thing we want to have them is in `Spryker\Service\{ModuleName}\{ModuleName}ServiceInterface` correct?

**Comment by dereuromark** [comment]
Also, currently it only checks isPluginInterface() not if it is an actual plugin implementing it.
We dont put the tag on concrete plugins?

**Comment by dereuromark** [comment]
So talking with denis we want to have api tags also for implementing plugins.
We wont enforce this automatically now, also enforcing removal of invalid ones will be postponed.
