### ISSUE TITLE
Check Propel schema on long indexes 

### ISSUE THREAD

**Issue by PhilinTv** [spryker/code-sniffer#116]
We have only 63 (?) characters for Postgresql index names.

**Comment by dereuromark** [comment]
But is this code sniffer, or some CI check or the (long proposed) console:schema:validate command?
For me this might be a bit out of scope of a CS tool IMO.

**Comment by dereuromark** [comment]
protected function validateAttribute(SimpleXMLElement $toXmlElement, string $key, string $value, string $fileName): void

should be further extended with such specific rules here.
