### ISSUE TITLE
License file doc blocks must be corrected

### ISSUE THREAD

**Issue by dereuromark** [spryker/code-sniffer#123]
The license doc blocks are not valid as per specs.
They must be

```
/*
 * Copyright ...
 */
```
instead of 
```
/**
 * Copyright ...
 */
```

The latter is only valid for methods, attributes, classes/interfaces directly, not for the top of files.
See symfony etc

**Comment by ravage84** [comment]
Where does your statement that two stars for a file doc block come from?

https://docs.phpdoc.org/getting-started/your-first-set-of-documentation.html

Shows two stars for file doc blocks.

Proposed PSR-5 also lists "file" as a valid doc block "Structural Element":

https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#3-definitions

**Comment by dereuromark** [comment]
Interesting, maybe this changed.
Not too long ago there was the resource that showed that doc block is only for structural elements, file legalinfo is more a comment..
Closing then.
