### ISSUE TITLE
Methods in one line

### ISSUE THREAD

**Issue by tamasnyulas** [spryker/code-sniffer#133]
Methods not longer than ~160 chars shouldn't be broken into several lines, this makes the code harder to read for no reason.

Before:
```
    public function foo(
        string $bar,
        int $baz
    ): void;
```
After:
```
    public function foo(string $bar, int $baz): void;
```

The next improvement could be to automatically break into lines per parameters when it's longer then the threshold.

**Comment by dereuromark** [comment]
https://github.com/spryker/code-sniffer/pull/212
