### ISSUE TITLE
Does not work with latest version of slevomat/coding-standard

### ISSUE THREAD

**Issue by marcingy** [spryker/code-sniffer#160]
slevomat/coding-standard 5.x.x has been released while this is locked at 4.8.x.

**Comment by dereuromark** [comment]
Do you know if we can just upgrade? https://github.com/spryker/code-sniffer/blob/master/composer.json#L16
Or are those completely incompatible?

If you can, please make a PR here.

**Comment by dereuromark** [comment]
If both work fine, we can use `4 || 5` here and release a simple patch.

**Comment by dereuromark** [comment]
Lets try to get https://github.com/spryker/code-sniffer/issues/160 passing

**Comment by dereuromark** [comment]
https://github.com/slevomat/coding-standard/issues/632 forces us to revert for now.
We will investigate the next days.

**Comment by dereuromark** [comment]
@marcingy Now fixed in master for good. Soon we tag a new patch release here.
