### ISSUE TITLE
var null|x issue of order

### ISSUE THREAD

**Issue by dereuromark** [spryker/code-sniffer#173]
Currently null|... is only fixed for method input/ioutput
Should also work for properties, though.

    /**
     * @var null|string
     */
    protected $organization;

=> 

    /**
     * @var string|null
     */
    protected $organization;

**Comment by gerner-spryker** [comment]
bugfix/variable-null-type-last

**Comment by dereuromark** [comment]
Resolved with https://github.com/spryker/code-sniffer/pull/178
