### ISSUE TITLE
array_key_exists sniffer

### ISSUE THREAD

**Issue by stereomon** [spryker/code-sniffer#19]
`isset()` should be used instead.

**Comment by marius-rizac** [comment]
```php
$array = [
    'a' => null,
];

var_dump(isset($array['a'])); // false (validates against the value)
var_dump(array_key_exists('a', $array)); // true 
```

It should be noted that they are not identical, though -- when the array key exists but the value is null, isset will return false and array_key_exists will return true. If the value may be null, you need to use array_key_exists.

**Comment by dereuromark** [comment]
I would not create a sniffer here as array_key_exists() is useful in some cases.
So this should be simple guideline in the docs/coding-standards section about preference and when to use what.
