### ISSUE TITLE
QueryContainer should not leave Persistence layer, DB schema should not be leaking outside of it 

### ISSUE THREAD

**Issue by the-colorant** [spryker/code-sniffer#20]
We need an architecture sniffer here first, then have a concrete list of bundles affected and in need of fixing.

**Comment by dereuromark** [comment]
Wrong repo, this is code sniffer:
=> https://github.com/spryker/architecture-sniffer

**Comment by the-colorant** [comment]
Issue moved to [spryker/architecture-sniffer #5](https://github.com/spryker/architecture-sniffer/issues/5) via [**ZenHub.io**](https://www.zenhub.io/)
