### ISSUE TITLE
Please allow to add ignores in our wrapper

### ISSUE THREAD

**Issue by vlunov-spryker** [spryker/code-sniffer#21]
We have to replace whole methods to add path ignores: https://github.com/spryker/spryker/blob/master/Bundles/Development/src/Spryker/Zed/Development/Business/CodeStyleSniffer/CodeStyleSniffer.php#L77

Could you please make it more flexible and allow to easily override it?

**Comment by dereuromark** [comment]
You can already exclude by having your own sniffer ruleset that extends the core one.
