### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by levacic** [spryker/code-sniffer#213]
Can you please publish a new release of the package?

The latest release `0.14.2` has `slevomat/coding-standard` locked at version `^4.8.7 || ^5.0.4`, but the newest release of `slevomat/coding-standard` is `6.1.5` - and this seems to have already been updated in your codebase, but you didn't publish a newer release.

I also suggest always publishing a new release after updating any of your dependencies, so that package users who also explicitly depend on your dependencies can upgrade everything - e.g. we're currently stuck and unable to upgrade `slevomat/coding-standard` to the latest release because of `spryker/code-sniffer`.

Thanks!

**Comment by dereuromark** [comment]
This is actually what we are preparing right now :)
We do final internal QA and once all is done, we are releasing a new (semantic) major here for all customers.

**Comment by levacic** [comment]
Thanks for the (very) fast reply.

We're not fans of `dev-master` so we'll wait for the new release. We are, however, fans of linters and enforcing coding standards, so we appreciate all the hard work and the awesome package.

Cheers!

**Comment by dereuromark** [comment]
dev-master with a commit hash lock is considered reliable. But sure, it cannot be more than one day away :)

**Comment by dereuromark** [comment]
We released :)
