### ISSUE TITLE
Please allow private members in CS for project scope

### ISSUE THREAD

**Issue by dereuromark** [spryker/code-sniffer#22]
When we run on project, which uses private:
`vendor/bin/phpcs /data/shop/development/current/src/Pyz --standard=/data/shop/development/current/vendor/spryker/code-sniffer/Spryker/ruleset.xml --ignore=vendor/`

We receive:
 `15 | ERROR | [x] Pyz\Yves\Cart\CartFactory::test is private.`

We should allow privates for the project scope.

PS: the same happens, when run through our wrapper.

**Comment by vlunov-spryker** [comment]
The fix looks fine 👍 , unfortunately I am unable to test it now in project.
