### ISSUE TITLE
Spryker.Commenting.DocBlockThrows.ThrowSuperfluous false positive

### ISSUE THREAD

**Issue by levacic** [spryker/code-sniffer#223]
Having an exception class defined with a static factory method:

```php
class InvalidFoo extends RuntimeException
{
    /**
     * Create a new exception instance.
     *
     * @return self
     */
    public static function create(): self
    {
        return new self('Invalid foo.');
    }
}
```

The following code triggers `Spryker.Commenting.DocBlockThrows.ThrowSuperfluous`:

```php
class Bar
{
    /**
     * @throws InvalidFoo
     *
     * @return void
     */
    public function baz(): void
    {
        throw InvalidFoo::create();
    }
}
```

The following code doesn't:

```php
class Bar
{
    /**
     * @throws InvalidFoo
     *
     * @return void
     */
    public function baz(): void
    {
        $exception = InvalidFoo::create();

        throw $exception;
    }
}
```

**Comment by dereuromark** [comment]
This should be solved with https://github.com/spryker/code-sniffer/pull/222
Please confirm

**Comment by levacic** [comment]
@dereuromark Indeed it works correctly when using the `bugfix/mp-3261-sniffer-removes-throw-annotation` - I searched for similar issues but didn't think to check out PRs and other branches, apologies for the noise.

Thanks for the quick response!
