### ISSUE TITLE
self this invalid change

### ISSUE THREAD

**Issue by dereuromark** [spryker/code-sniffer#224]
>  139 | ERROR | [x] self => $this (Spryker.Commenting.DocBlockReturnSelf.SelfVsThis)

In

    /**
     * @param string $alias alias for the subQuery
     *
     * @return self
     */
    public function getSelectQuery($alias)
    {
        return $this->selectQueries[$alias];
    }

**Comment by levacic** [comment]
The related PR makes the following code invalid:

```
/**
 * Foo.
 *
 * @return $this
 */
public function foo(): self
{
    return $this->bar()->baz();
}
```

(where course both `bar()` and `baz()` return `$this`, and are documented with `@return $this`).

The `Spryker.Commenting.DocBlockReturnSelf.InvalidChainable` gets triggered in this situation, whereas the following code passes without errors:

```
/**
 * Foo.
 *
 * @return $this
 */
public function foo(): self
{
    $this->bar()->baz();

    return $this;
}
```

What's the reasoning behind the change? The first (previously valid) code seems more readable to me, although I kind of see that it relies on each of the chained methods returning `$this` as well - whereas the latter doesn't. Is that it?

**Comment by dereuromark** [comment]
Yes, we want to enforce a higher reliability on chainable to actually return the same object, rather than a clone or fresh static.
So this was about the only way to safely ensure this.
