### ISSUE TITLE
Comments with class-hints

### ISSUE THREAD

**Issue by the-colorant** [spryker/code-sniffer#24]
Original issue: https://github.com/spryker/spryker/issues/1468

We need specific class-hints in dock-blocks. E.g. we need this in any controller of the discount-bundle:

```
/**
 * @method \Spryker\Zed\Discount\Communication\DiscountCommunicationFactory getFactory()
 * @method \Spryker\Zed\Discount\Business\DiscountFacade getFacade()
 * @method \Spryker\Zed\Discount\Persistence\DiscountQueryContainer getQueryContainer()
 */
```

Please a sniffer which adds missing `@method`s. It does not change existing ones! Of course the sniffer only adds if there is a related factory, facade or query container. In project code it prefers the ones from project, ~~but falls back to the ones from core~~ (not needed then as core already got them).

This is needed for:
- Controllers
- QueryContainer
- Client
- (Where else?)

**Comment by dereuromark** [comment]
should be done
