### ISSUE TITLE
Final private sniff

### ISSUE THREAD

**Issue by dereuromark** [spryker/code-sniffer#241]
> PHP Warning:  Private methods cannot be final as they are never overridden by other classes

    final private function __construct()
    {
    }

should be

    final public function __construct()
    {
    }

same for other magic methods or all methods in general.

For PHP8

**Comment by alfredbez** [comment]
This should affect only private methods, but not protected methods, see https://3v4l.org/8WIVO

```php
<?php
class Foo {
    final protected function bar() {
        echo 'baz';
    }
    
    public function triggerProtected() {
        $this->bar();
    }
    
    final private function bar1() {
        echo 'baz1';
    }
    
    public function triggerPrivate() {
        $this->bar1();
    }
}

(new Foo())->triggerProtected();
(new Foo())->triggerPrivate();
```
```
Warning: Private methods cannot be final as they are never overridden by other classes in /in/8WIVO on line 11
bazbaz1
```
