### ISSUE TITLE
0.16.0 breaks PHP 7 code

### ISSUE THREAD

**Issue by alfredbez** [spryker/code-sniffer#256]
We did the upgrade to `0.16.0` and noticed that `SlevomatCodingStandard.Classes.ModernClassNameReference.ClassNameReferencedViaFunctionCall` broke our code at some places, by replacing `get_class($boolQuery)` with `$boolQuery::class` (which only works with PHP 8).

The parent rule is included here: https://github.com/spryker/code-sniffer/blob/d33f16b1f3fd60ace01c73b74ed49846e99b1400/Spryker/ruleset.xml#L52

**Comment by dereuromark** [comment]
Is that an issue we should open on their repo instead?

**Comment by dereuromark** [comment]
It looks like this sniff was already part of 0.15.
So if there is a bug here I assume that https://github.com/slevomat/coding-standard/issues should be the tracker for it, as we could only silence the sniff, but not fix the root cause.

**Comment by alfredbez** [comment]
Stupid me executed that on my host while using PHP 8.0, works perfectly if I use that with PHP 7.
