### ISSUE TITLE
FQCN Docblock/Body fixer influence each other

### ISSUE THREAD

**Issue by lmanzke** [spryker/code-sniffer#28]
Consider this Factory class:

```
<?php

namespace Pyz\Zed\Example\Business;

use Pyz\Zed\Example\ExampleConfig;
use Spryker\Zed\Kernel\Business\AbstractBusinessFactory;

/**
 * @method \Pyz\Zed\Example\ExampleConfig getConfig()
 * @method \Pyz\Zed\Example\Persistence\ExampleQueryContainerInterface getQueryContainer()
 */
class ExampleBusinessFactory extends AbstractBusinessFactory
{

    /**
     * @return ExampleConfig
     */
    public function createMyTestClass()
    {
        return new \Pyz\Zed\Example\ExampleConfig();
    }
    
}
```

While architecture-wise, this one function does not make sense, it reveals a bug by the fixers:

If you run the standard fixer-set over this code, you'll get:

```
<?php

namespace Pyz\Zed\Example\Business;

use Spryker\Zed\Kernel\Business\AbstractBusinessFactory;

/**
 * @method \Pyz\Zed\Example\ExampleConfig getConfig()
 * @method \Pyz\Zed\Example\Persistence\ExampleQueryContainerInterface getQueryContainer()
 */
class ExampleBusinessFactory extends AbstractBusinessFactory
{

    /**
     * @return \Pyz\Zed\Example\ExampleConfig
     */
    public function createMyTestClass()
    {
        return new ExampleConfig();
    }

}
```

This is **almost** correct, but it won't work. The import for the example config has been wrongly removed and thus is unknown inside of createMyTestClass. The problem is that one fixer removes the FQCN in the method block (which is correct), adding the import statement. The next fixer, however, **adds** the FQCN to the docblock (which is also correct), but in turn removes the use statement. The problem occurs because, during fixing, there is a point where the fixer thinks the import is unused and removes it (and that is because the class is still fully qualified in the method block). That should be changed.

**Comment by dereuromark** [comment]
Resolved with https://github.com/spryker/code-sniffer/commit/62ae9b1d13941bbdbf23ac04234c91d550435692 - please confirm.

**Comment by lmanzke** [comment]
Confirmed working now. Had no cases left.
