### ISSUE TITLE
Multi-byte string operations 

### ISSUE THREAD

**Issue by the-colorant** [spryker/code-sniffer#31]
All string operations must be multibyte compatible. That's why we need a code sniffer to detect cases where we don't use multi-byte string operations.

**Comment by dereuromark** [comment]
I disagree.  We don't have any issues here right now.

**Comment by the-colorant** [comment]
Then we can just close this issue and create one when we need?

**Comment by dereuromark** [comment]
Yep. Currently we use common sense to add it where necessary.
Future PHP versions will automatically make this a no-issue completely then.
