### ISSUE TITLE
Wrong @throw annotation suggested

### ISSUE THREAD

**Issue by alfredbez** [spryker/code-sniffer#316]
We found a weird bug in the code-sniffer, that can be reproduced with this minimal example:
```php
<?php

declare(strict_types = 1);

namespace Pyz;

use Lcobucci\JWT\Parser;
use League\OAuth2\Server\Exception\OAuthServerException;

class Foo
{
    /**
     * @throws \League\OAuth2\Server\Exception\OAuthServerException !
     *
     * @return void
     */
    public function bar(): void
    {
        throw OAuthServerException::accessDenied('baz');

        new Parser();
    }
}
```
Output of `phpcs`:
```
-------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
-------------------------------------------------------------------------------------------------------------------------------
 16 | ERROR   | [x] Doc Block @throw annotation `Lcobucci\JWT\Parser` missing
    |         |     (Spryker.Commenting.DocBlockThrows.ThrowMissing)
 21 | WARNING | [ ] Code after the THROW statement on line 19 cannot be executed (Squiz.PHP.NonExecutableCode.Unreachable)
-------------------------------------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
-------------------------------------------------------------------------------------------------------------------------------
```

Somehow the code-sniffer suggests, that `Lcobucci\JWT\Parser` should be thrown, but this is not even a valid exception class.

----

We use these versions:
| Package | Version |
| --- | --- |
| `spryker/code-sniffer` | 0.17.3 |
| `lcobucci/jwt` | 3.4.4 |
| `league/oauth2-server` | 7.4.0 |

**Comment by alfredbez** [comment]
I think stepping through [`\Spryker\Sniffs\Commenting\DocBlockThrowsSniff::extractExceptions`](https://github.com/spryker/code-sniffer/blob/489fc77344682f9357c2ba4a09281fa741ea67cf/Spryker/Sniffs/Commenting/DocBlockThrowsSniff.php#L95) could shed some light on this.

**Comment by dereuromark** [comment]
> `Doc Block @throw annotation`

`@throw` vs `@throws` maybe as well
At least the message seems to be not using the s it should.

**Comment by dereuromark** [comment]
I think I know what it is

    throw ...::...('baz');

vs

    throw new ...();
    throw $e;
    
So far it only understands newable or variable usage.

**Comment by dereuromark** [comment]
Please check PR.
