### ISSUE TITLE
Remove Composer tool related code

### ISSUE THREAD

**Issue by szepeviktor** [spryker/code-sniffer#334]
From  #333

`spryker/code-sniffer` is a Composer package. A user without installed Composer tool cannot participate in this ecosystem.

[Proper installation](https://github.com/szepeviktor/debian-server-tools/blob/master/debian-setup/packages/_package-php-composer).

I propose to remove all traces and add a link to README: https://getcomposer.org/doc/00-intro.md

@dereuromark Is it okay with you?

**Comment by dereuromark** [comment]
What is the goal here?
To make it easier to get installed without composer?
Is that even a thing these days still?

**Comment by szepeviktor** [comment]
Do you think showing how to install Composer (the tool) helps your users?

**Comment by szepeviktor** [comment]
In other words: is there a single person who starts using `spryker/code-sniffer` **before** installing Composer on his machine?
