### ISSUE TITLE
Remove stray/legacy .license file

### ISSUE THREAD

**Issue by szepeviktor** [spryker/code-sniffer#336]
@dereuromark Is it okay with you?

**Comment by szepeviktor** [comment]
Oh no!
https://github.com/spryker/code-sniffer/blob/acb02cb4cf78dcab323491ea7bc8f5e813adc762/Spryker/Sniffs/Commenting/FileDocBlockSniff.php#L15

Shouldn't the expected file docblock content be in `phpcs.xml`?

**Comment by dereuromark** [comment]
We use that file on purpose. As it is needed for our company wide license validation/assertion.

**Comment by szepeviktor** [comment]
Could you imagine that its contents goes inside `phpcs.xml`?

**Comment by dereuromark** [comment]
I dont see why it would need to.
lets try to improve this lib, not change things that have little value to change.

**Comment by szepeviktor** [comment]
> not change things that have little value to change.

I'm sorry. I'm a big friend on little values. Actually I caring about the foundation, developers do the pioneer work.

**Comment by dereuromark** [comment]
Sure, but each change also needs to understand and reflect the environment and BC.
Changing this can have some side effects for our existing libraries, so we need to understand the value for such little changes in order not to risk more negative impact than the benefit they bring.

**Comment by szepeviktor** [comment]
One less file would warm my heart and pay for all negative impacts :)

**Comment by dereuromark** [comment]
We created and maintain this library of thousands of customers and developers.
Keep that in mind, please.

**Comment by szepeviktor** [comment]
You caught me dreaming!
I'm no businessman.
