### ISSUE TITLE
Obey PHPCSDevCS coding standard

### ISSUE THREAD

**Issue by szepeviktor** [spryker/code-sniffer#337]
Please see https://github.com/PHPCSStandards/PHPCSDevCS

@dereuromark Is it [okay](https://github.com/spryker/code-sniffer/blob/c97d532e3bda7f4deb7fff05ae5fe509d965ab51/phpcs.xml#L16) with you?

**Comment by dereuromark** [comment]
Why this one?
Our company CS follows a different one.

**Comment by szepeviktor** [comment]
Its description says: _External ruleset for PHP CodeSniffer **intended for use by sniff developers**_

I know PHPCS is very much a PHP4 tool but we extend them, not the other way.

**Comment by dereuromark** [comment]
But we hold the library to a higher standard, using also our own sniffs.
So it doesnt not seem right to change this for the sake of changing.
