### ISSUE TITLE
Allow using cache

### ISSUE THREAD

**Issue by localheinz** [spryker/code-sniffer#341]
According to the documentation for [`squizlabs/php_codesniffer`](https://github.com/squizlabs/PHP_CodeSniffer), a `--cache` option can be used to enable the cache and specify a cache file.

As far as I can tell, it is currently not possible to specify a cache file when running

```shell
vendor/bin/console code:sniff:style
```

or

```shell
vendor/bin/console code:sniff:style --fix
```

How do you feel about allowing to specify the `--cache` option?

**Comment by dereuromark** [comment]
How much performance does it bring?
In general I would recommend using -d to output the command raw and then copy and paste this one for customized runs (e.g. from IDE).

But sure, we can add also cache option to the wrapper. Feel free to make a PR here.

**Comment by localheinz** [comment]
@dereuromark 

I believe it makes more sense to use `squizlabs/php_codesniffer` directly, then - not sure why the wrapper exists in the first place.

Thank you!
