### ISSUE TITLE
New sniff: Throwing exceptions with empty messages

### ISSUE THREAD

**Issue by lmanzke** [spryker/code-sniffer#37]
Exceptions with empty messages can be frustrating because they lack valuable information.
Often, this information is present when throwing the exception, but is not passed in (example: Invalid order because an order could not be find by reference - here, the reference would be a useful info)

There is no reason why an empty exception message makes sense and a sniffer should be relatively straightforward - with good benefits for later debugging.

**Comment by dereuromark** [comment]
We currently have 57 occurrences of this in the core currently.
But I would say this is prio very low at this point.

**Comment by tamasnyulas** [comment]
I think we have some exceptions where the message is set in the class itself, not when it's instantiated, however I also prefer to pass the message and all the possible info when the exception is thrown.

**Comment by lmanzke** [comment]
This is still open - and there are cases where it would be useful to have a message :)

**Comment by dereuromark** [comment]
Someone would have to make PRs here.
