### ISSUE TITLE
Upgrade to CS3

### ISSUE THREAD

**Issue by dereuromark** [spryker/code-sniffer#39]
It will soon become stable and will be namespaced (php5.4+) finally.
https://github.com/squizlabs/PHP_CodeSniffer/tree/3.0

https://github.com/cakephp/cakephp-codesniffer/pulls is already doing it right now in PR 160.
We can leverage that knowledge I think.

**Comment by lmanzke** [comment]
If cake is doing it, we sure can 😆

**Comment by TomasVotruba** [comment]
Btw, did you consider using them both - PHP_CodeSniffer and PHP CS Fixer?

**Comment by dereuromark** [comment]
What's the fixer you mean?
afaik it doesn't provide anything beyond what the sniffer (currently used) doesn't already provide out of the box. both sniffing and fixing etc.

**Comment by TomasVotruba** [comment]
But don't take my word for it, look at these 5 projects that are already using them both: https://github.com/symplify/easyCodingStandard/#the-easiest-way-to-use-any-coding-standard

And their sets:

- https://github.com/shopsys/coding-standards/blob/master/easy-coding-standard.yml
- https://github.com/nette/coding-standard/blob/master/coding-standard-php56.neon
- https://github.com/SyliusLabs/CodingStandard/blob/master/easy-coding-standard.yml
- https://github.com/lmc-eu/php-coding-standard/blob/master/easy-coding-standard.yaml
- https://github.com/sunfoxcz/coding-standard/blob/master/config/sunfox.yml

**Comment by dereuromark** [comment]
> new sniffs and fixers that nobody ever made before

Oh, dont wry, I did all that before already :)

I know what you mean, but for the few percent we are currently maybe missing there is not too much interest in combining yet another tool to be used and maintained.
We can revisit this in the future, though. Thanks for the heads up.

**Comment by TomasVotruba** [comment]
> ...but for the few percent we are curently maybe missing...

I looked into the Spyker coding standard before and I saw some very advanced architectonical sniffs, so I think you're quite strict to the code (which is great). I think it would be about 30-40 extra rules you're missing (from fixes I know about now)

> ...there is not too much interest in combining 

It's not combination, it's simpler replacement with focus on DX.

> We can revisit this in the future, though. Thanks for the heads up.

Sure, I'll be waiting :+1:   ;)
