### ISSUE TITLE
Add interface vs class doc block description sniff

### ISSUE THREAD

**Issue by dereuromark** [spryker/code-sniffer#44]
We need a sniffer to assert that the

```
/**
     * Specification:
     *  - ...
     *
     * @api
     *
```

part is consistent for class and the implemented interface!

Only assert, no auto-fix to avoid killing the wrong version. Must be resolved manually.

**Comment by a-sabaa** [comment]
Only remove if duplicate content, otherwise show error to resolve manually

**Comment by dereuromark** [comment]
{inheritDoc} solved this.
