### ISSUE TITLE
File Doc block issue

### ISSUE THREAD

**Issue by dereuromark** [spryker/code-sniffer#58]
```
<?php

namespace Unit\Spryker\Zed\Gui\Communication\Fixture;
```

Gets the namespace keyword killed when running fixer,
and replaced by copyright text
```
/**
 * Copyright © 2016-present Spryker Systems GmbH. All rights reserved.
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */
Unit\Spryker\Zed\Gui\Communication\Fixture;
```

**Comment by dereuromark** [comment]
The problem is that this sniff does not check on composer file and isDemoshop() but uses the namespace still (Pyz)
This needs fixing soon.
If anyone can help, that would be great.

**Comment by dereuromark** [comment]
Optional improvement on top:

Allow projects to have their own meta file somewhere that contains their project template for file doc block, e.g. a dot file `.license` etc.
If the sniffer finds this in root it will then use that one instead instead of just skipping.

This must not afffect Spryker or SprykerEco or any other vendor namespace of course.

**Comment by lazystar** [comment]
I would suggest to move the `ruleset.xml` to project level and make it more verbose, meaning explicitly loading the sniffs. Projects then have the desired defaults and can then adjust the file at will.

**Comment by dereuromark** [comment]
We can add one additionally. But the main one needs to stay so it can work standalone (out of the box) via vendor/bin/phpcs etc.

**Comment by lazystar** [comment]
the only thing that would have to change is the default location in `code:sniff`

**Comment by dereuromark** [comment]
Fixed with https://github.com/spryker/code-sniffer/commit/6b0081120f8ea152f49f5ac1d5709889b7a7386a for now.
