### ISSUE TITLE
SprykerFacadeSniff does not work correctly in PhpStorm IDE

### ISSUE THREAD

**Issue by darius-telycenas** [spryker/code-sniffer#63]
`SprykerFacadeSniff` fails when using in `IDE` (PhpStorm becomes annoying):

<img width="622" alt="screen shot 2017-02-14 at 22 38 34" src="https://cloud.githubusercontent.com/assets/2518048/22950691/c9879410-f306-11e6-8eff-142b79080c92.png">

The reason is that `PhpStorm` uses `tmp` folders for caching (and local changes history), and `SprykerFacadeSniff` uses `file_exists` to check if `XyzFacade` has `XyzFacadeInterface` at the same location (which is not the case with `tmp` folder structure of `IDE`, and additionally `file_get_contents` fails for the same reason:

<img width="995" alt="screen shot 2017-02-14 at 22 39 06" src="https://cloud.githubusercontent.com/assets/2518048/22950695/cc593df6-f306-11e6-942c-64d3bb175901.png">

**Comment by dereuromark** [comment]
What would you suggest we do here?

**Comment by darius-telycenas** [comment]
Actually, it is `php_cs` which creates `tmp` files from current editor window in `IDE`…

`class PHP_CodeSniffer_Reporting` has some hints about dealing with `tmp` files — a simplified version:
```
                $metaData = stream_get_meta_data($tmpFile);
                $fileName = $metaData['uri'];
                $contents = file_get_contents($filename);
```
*Note:* this is not tested yet, but could work ;)

**Comment by dereuromark** [comment]
If you have a concrete solution please PR it for us to investigate :)

**Comment by dereuromark** [comment]
any update here if we need to do sth - or can do sth?

**Comment by darius-telycenas** [comment]
Re-checked — no issues any more, cannot reproduce this.

Issue can be closed.
