### ISSUE TITLE
Sniffer crashes on single-line dockblocks

### ISSUE THREAD

**Issue by ievgenvarava** [spryker/code-sniffer#78]
Steps to reproduce:
* Add new class into project and add a single-line dockblock to it's method:
```
<?php

class Test
{
    /** @return bool */
    public function test()
    {
        return true;
    }
}
```
* Run code sniffer with `vendor/bin/console code:sniff`

**Actual behaviour**
Sniffer crashes with error
```
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes) in /data/shop/development/current/vendor/spryker/code-sniffer/Spryker/Sniffs/Commenting/DocBlockTagGroupingSniff.php on line 245
```

**Expected behaviour**
Sniffer should handle (and fix automatically if -f option is selected) given dockblock

**Comment by darius-telycenas** [comment]
Could be somehow related to https://github.com/squizlabs/PHP_CodeSniffer/issues/258
