### ISSUE TITLE
File Doc block fixer should only run when file was modified

### ISSUE THREAD

**Issue by stereomon** [spryker/code-sniffer#8]
Currently the File Doc Block sniffer would change all file doc blocks when the year doesn't match anymore. The fixer should only run when the file was changed in the current year. This can be checked with filemtime

**Comment by dereuromark** [comment]
We should re-discuss the need for it again in a weekly prior to 31.12.2016.

**Comment by dereuromark** [comment]
We hardcoded 2016 for now, It should actually never change and ideally be a fixed starting point.
otherwise we are lying to everyone.
