### ISSUE TITLE
Api tag should come after inheritdoc.

### ISSUE THREAD

**Issue by lmanzke** [spryker/code-sniffer#83]
Just got a comment from @tamasnyulas and realized that 
```
/**
     * @api
     *
     * {@inheritdoc}
     *
     * @param \Generated\Shared\Transfer\OrderTransfer $orderTransfer
     *
     * @return \Generated\Shared\Transfer\OrderTransfer
     */
``` 
should be fixed to 
```
/**
     * {@inheritdoc}
     *
     * @api
     *
     * @param \Generated\Shared\Transfer\OrderTransfer $orderTransfer
     *
     * @return \Generated\Shared\Transfer\OrderTransfer
     */
```

I think a fixer for that would be a good idea.

**Comment by dereuromark** [comment]
Unfortunately, this is not possible
since in the middle of @ tag annotations those technically belong to the one above.

This here is valid from the phpcs point of view. not sure what we can and should do here..

**Comment by dereuromark** [comment]
It is probably better to move this over to the https://github.com/spryker/architecture-sniffer/blob/master/src/Client/ClientRule.php rule in arch. sniffer, and also add the inheritdoc part as well as the order :)

**Comment by dereuromark** [comment]
Also this should be resolved
```php
    /**
     * @deprecated Will be removed without replacement.
     *
     * @see \Symfony\Contracts\Translation\TranslatorInterface
     *
     * {@inheritdoc}
     *
     * @api
     *
     * @param string $locale
     *
     * @return void
     */
```
to
```php
    /**
     * {@inheritdoc}
     *
     * @api
     *
     * @deprecated Will be removed without replacement.
     *
     * @see \Symfony\Contracts\Translation\TranslatorInterface
     *
     * @param string $locale
     *
     * @return void
     */
```
etc

**Comment by dereuromark** [comment]
We can write an own sniffer for this.

**Comment by dereuromark** [comment]
Fixed with https://github.com/spryker/code-sniffer/pull/188
